import telebot
from telebot import types

# insérer votre code API ici
bot = telebot.TeleBot("6259737243:AAHMGjisO3jCIpZtLJSUbM1lV4_U68_RKm4")


# code pour envoyer un GIF d'accueil
@bot.message_handler(commands=['start'])
def send_welcome(message):
    chat_id = message.chat.id
    animation_url = "https://media.giphy.com/media/ohkdbwhfqQCFq/giphy.gif" # remplacer avec votre propre GIF
    bot.send_animation(chat_id, animation_url, caption="Welcome to you, my name is DDREAM_Bot, the assistant of Nayar1416. \nVisit all the channels at https://t.me/Alllink_nayar1416")
    markup = telebot.types.ReplyKeyboardMarkup(row_width=2)
    itembtn0 = telebot.types.KeyboardButton(' /start')
    itembtn1 = telebot.types.KeyboardButton(' /spicy')
    itembtn2 = telebot.types.KeyboardButton(' /leaked')
    itembtn3 = telebot.types.KeyboardButton('/custom')
    itembtn4 = telebot.types.KeyboardButton('/process')
    markup.add(itembtn0,itembtn1, itembtn2, itembtn3, itembtn4)
    bot.send_message(chat_id, "Here you will find everything you are looking for. \nDifferent options are available to you:\n\U0001F336Spicy: Access to content generated via AI \n\U0001F4F9Leaked: Access to X leaked content such as OF, Mym, or big production house \n\U0001F381Custom: Custom content \n\u2705Process: Information about my work and how I go about offering you all this great content", reply_markup=markup)


####################### code pour les commandes '/process'
@bot.message_handler(commands=['process'])
def handle_process_command(message):  
    chat_id = message.chat.id
    bot.send_message(chat_id, "Are you interested in my work? Would you like to learn more about it so you can do the same? \nI'll give you a general overview of how I work. \nIf you want to know more, send an email to nayar1416@gmail.com and we will discuss together if you have any questions. I work with Stable diffusion, version AUTOMATIC1111. Many tutorials exist on the internet for the installation and the handling.\nMy images will be in 900x900 format.\nDifferent models exist on the internet. The models are files with theme, one will be oriented animated style/manga, the other will be oriented realism of the human body for example etc, of many models exist.\nThe idea will be even to mix the models in order to optimize the results. \nSo I propose custom generated content for the most fetish of you. \nAlso the access to many OF and pro content allows me to share EXCLUSIVE content with you. ")
    bot.send_message(chat_id, "Return to the main menu --> /start")
    

####################### code pour les commandes '/spicy'
@bot.message_handler(commands=['spicy'])
def handle_spicy_command(message):  
    chat_id = message.chat.id
    bot.send_message(chat_id, "You have chosen the command /spicy. \nYou'll soon have access to images generated by my AI, whole images of your favourite actresses, naked and in lingerie 🥵, from your favourite movies. \nExamples include Scarlett Johansson, Emilia Clarke, Natalie Portman, Emma Stone and many more. Do you prefer an actress with more than 50 pictures or the full bundle (more competitive rate!)?")
    bot.send_message(chat_id, "Below is the complete list, if you can't find the actress, let me know by email below, I'll see if I can help you \U0001F607.")
    photo_url = 'https://i12.bunkr.ru/00113-208024350-FflXcNgO.png' 
    bot.send_photo(chat_id, photo_url, reply_markup=markup_spicy)
markup_spicy = telebot.types.InlineKeyboardMarkup(row_width=1)
itembtn5 = telebot.types.InlineKeyboardButton("An actress only", callback_data='An actress only')
itembtn6 = telebot.types.InlineKeyboardButton("The complete bundle!", callback_data='The complete bundle!')
itembtn7= telebot.types.InlineKeyboardButton("Mail access", callback_data='Mail access')
markup_spicy.add(itembtn5, itembtn6, itembtn7)


####################### code pour les commandes '/leaked'
@bot.message_handler(commands=['leaked'])
def handle_leaked_command(message):  
    chat_id = message.chat.id
    bot.send_message(chat_id, "You have chosen the /leaked command. \nHere you will have access to hundreds of GB of content kindly borrowed to satisfy you.\U0001F4A6 \nImagine your favorite actresses, pro or amateur, you will discover them as if you had a subscription to their private OF.")
    bot.send_message(chat_id, "Below is the complete list, if you can't find the actress, let me know by email below, I'll see if I can help you \U0001F607.")
    photo_url = 'https://i12.bunkr.ru/PRESENTATION-bxL3OGXk.jpg' 
    bot.send_photo(chat_id, photo_url, reply_markup=markup_leaked)
markup_leaked = telebot.types.InlineKeyboardMarkup(row_width=1)
itembtn8 = telebot.types.InlineKeyboardButton("An actress", callback_data='An actress')
itembtn9 = telebot.types.InlineKeyboardButton("Complete package", callback_data='Complete package')
itembtn10 = telebot.types.InlineKeyboardButton("Mail access", callback_data='Mail access')
markup_leaked.add(itembtn8, itembtn9, itembtn10)



####################### code pour les commandes '/custom'
@bot.message_handler(commands=['custom'])
def handle_custom_command(message):  
    chat_id = message.chat.id
    bot.send_message(chat_id, "You have chosen the /custom command. \nThings are about to get interesting here. \nThis custom service will allow you to imagine a scene or an image, or even several, that I generate for you thanks to AI. \nDepending on what you wish, we can exchange by mail or via TELEGRAM so that you can tell me more. \nSend me a maximum of details and let your imagination run free \U0001F680")
    photo_url = 'https://i9.bunkr.ru/Sans-titre-M5nuoXYz.png' 
    bot.send_message(chat_id, "In the example below, I have created Emilia Clarke, as Daenerys Targaryen, with her brown clone \U0001F648")
    bot.send_photo(chat_id, photo_url, reply_markup=markup_custom)
markup_custom = telebot.types.InlineKeyboardMarkup(row_width=1)
itembtn11 = telebot.types.InlineKeyboardButton("Mail access", callback_data='Mail access')
markup_custom.add(itembtn11)

####################### code pour les réponses  
@bot.callback_query_handler(func=lambda call: True)
def callback_query_spicy(call):
    if call.data == 'An actress only': #POUR COMMANDE SPICY
        bot.answer_callback_query(callback_query_id=call.id)
        bot.send_message(call.message.chat.id, "Which actress would you like to discover?\U0001F970 \n•Scarlett Johansson \u2B50\u2B50\u2B50 \n•Emilia Clarke \u2B50\u2B50\u2B50 \n•Natalie Portman \u2B50\u2B50 \n•Ana de Armas\u2B50\u2B50\u2B50 \n•Jenna Ortega \u2B50\u2B50\u2B50 \n•Megan Fox\u2B50\u2B50\u2B50 \n•Zoe Saldana\u2B50\u2B50 \n•Anna Kendrick\u2B50\u2B50 \n•Jordana Brewster \u2B50\u2B50 \n•Mila Kunis \u2B50\u2B50 \n•Emma Watson \u2B50\u2B50\u2B50 \n•Margot Robbie \u2B50\u2B50\u2B50\n• Rose Leslie\u2B50\u2B50\n• Alexandra Daddario\u2B50\u2B50\n\n Write the name of the chosen actress in full")
        bot.register_next_step_handler(call.message, day_handler)
    elif call.data == 'The complete bundle!': #POUR COMMANDE SPICY
        chat_id = call.message.chat.id
        bot.send_message(chat_id, "Very good choice!\U0001f389\U0001f389 \n\nThe 700 photo bundle is only 99 euros \U0001f4c9 instead of €462. \nSend an email to nayar1416@gmail.com with the proof of paypal payment \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies reference code #1000_YOUR_TELEGRAM_NAME")
    elif call.data == 'Mail access' : #POUR COMMANDE LEAKED et SPICY
        chat_id = call.message.chat.id
        bot.send_message(chat_id, "My email: nayar1416@gmail.com.")
    elif call.data == 'Complete package': #POUR COMMANDE LEAKED
        chat_id = call.message.chat.id
        bot.send_message(chat_id, "You have chosen the complete bundle.\n The bundle is 49 euros for over 650 GB of content \U0001f3c6 (pictures + videos), for a value of more than 1000€ \U0001f92f.\nSend an email to nayar1416@gmail.com with the proof of paypal payment \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies reference code #5000_YOUR_TELEGRAM_NAME")
    elif call.data == 'An actress': #POUR COMMANDE LEAKED
        chat_id = call.message.chat.id
        bot.send_message(chat_id, "Which actress would you like to discover?\U0001F970 \n•Alice Red Lips \n•Alexa Thomas \n•Anya Olsen \n•Ariana Marie \n•Arilaviee \n•Belle Delphine \n•Marck Rockwell \n•Cherry Apricots \n•Connie Carter \n•Dainty Wilder \n•Elsa Jean \n•Gia Paige \n•Haileyhatezyou \n•Jamelizz \n•Kristen Hancher \n•Siemens Sofia \n•Lana Rhoades \n•Lilly Rae \n•Luma Skye \n•Mackenzie \n•Madison Ivy \n•Maliah Blake \n•Little Caprice \n•Melim TX \n•My Cherry Crush \n•Octokuro \n•Naomi Swann \n•Purple Bitch \n•Rae Lil Black \n•Brandi Love \n•Cat Kitty")
        bot.register_next_step_handler(call.message, day_handler1)

# réponses proposée pour les actrices du bouton "une actrice" de la commande /spicy
def day_handler(message):
    chat_id = message.chat.id
    if message.text == 'Scarlett Johansson':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #001_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Emilia Clarke':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #002_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Natalie Portman':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #003_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Ana de Armas':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #004_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Jenna Ortega':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #005_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Megan Fox':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #006_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Zoe Saldana':
        bot.send_message(chat_id, "25€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #007_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Ana Kendrick':
        bot.send_message(chat_id, "25€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #008_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Jordana Brewster':
        bot.send_message(chat_id, "25€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #009_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Mila Kunis':
        bot.send_message(chat_id, "25€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0010_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Emma Watson':
        bot.send_message(chat_id, "39€ for 50 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0011_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Margot Robbie':
        bot.send_message(chat_id, "39€ for 10 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0012_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Rose Leslie':
        bot.send_message(chat_id, "25€ for 10 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0013_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    elif message.text == 'Alexandra Daddario':
        bot.send_message(chat_id, "25€ for 10 photos, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0014_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /spicy or go back to the main menu with --> /start")
    else:
        bot.send_message(chat_id, "I do not know this actress. Please click on the *Actress only* button again and enter the full name of the actress --> /spicy \nOr return to the main menu --> /start")

# réponses proposée pour les actrices du bouton "une actrice seulement" de la commande /spicy
def day_handler1(message):
    chat_id = message.chat.id
    if message.text == 'Alice Red Lips':
        bot.send_message(chat_id, "10€ for 15 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #011_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Alexa Thomas':
        bot.send_message(chat_id, "5€ for 5,5 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #012_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Anya Olsen':
        bot.send_message(chat_id, "5€ for 2 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #013_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Arilaviee':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #014_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Belle Delphine':
        bot.send_message(chat_id, "5€ for 6 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #015_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Marck Rockwell':
        bot.send_message(chat_id, "5€ for 2 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #016_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Cherry Apricots':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #017_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Connie Carter':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #018_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Dainty Wilder':
        bot.send_message(chat_id, "10€ for 21 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #019_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Elsa Jean':
        bot.send_message(chat_id, "5€ for 1,2 GO, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0020_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Gia Paige':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #0021_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Haileyhatezyou':
        bot.send_message(chat_id, "10€ for 16 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0022_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Jamelizz':
        bot.send_message(chat_id, "5€ for 6 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0023_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Kristen Hancher':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #0024_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Siemens Sofia':
        bot.send_message(chat_id, "10€ for 14 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0025_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Lana Rhoades':
        bot.send_message(chat_id, "10€ for 13 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0026_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Lilly Rae':
        bot.send_message(chat_id, "10€ for 12 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0027_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Luma Skye':
        bot.send_message(chat_id, "10€ for 15 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0028_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Mackenzie':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #0029_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Madison Ivy':
        bot.send_message(chat_id, "25€ for 114 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0030_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Maliah Blake':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #0031_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Little Caprice':
        bot.send_message(chat_id, "10€ for 16 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0032_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Melim TX':
        bot.send_message(chat_id, "FREE, send an email to nayar1416@gmail.com \nSpecifies the reference code #0033_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'My Cherry Crush':
        bot.send_message(chat_id, "15€ for 22 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0034_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Octokuro':
        bot.send_message(chat_id, "5€ for 2 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0035_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Naomi Swann':
        bot.send_message(chat_id, "5€ for 3 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0036_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Purple Bitch':
        bot.send_message(chat_id, "5€ for 5 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0037_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Rae Lil Black':
        bot.send_message(chat_id, "25€ for 280 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0038_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Brandi Love':
        bot.send_message(chat_id, "25€ for 50 Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0039_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    elif message.text == 'Cat Kitty':
        bot.send_message(chat_id, "10€ for 20Go, send an email to nayar1416@gmail.com with the proof of paypal paymentpaypal \n--> https://www.paypal.com/paypalme/nayar1416 \nSpecifies the reference code #0040_YOUR_TELEGRAM_NAME")
        bot.send_message(chat_id, "Another one? Click on --> /leaked or go back to the main menu with --> /start")
    else:
        bot.send_message(chat_id, "I do not know this actress. Please click on the *Actress* button again and enter the actress' full name --> /leaked \nOr return to the main menu --> /start")


@bot.message_handler(commands=['actrice'])
def sign_handler(message):
    text = "Choose an option:  \n•One actress only \n• the complete package \n•Mail Access"
    sent_msg = bot.send_message(message.chat.id, text)
    bot.register_next_step_handler(sent_msg, callback_query_spicy)





        
# boucle pour garder le bot actif
bot.polling()


#6259737243:AAHMGjisO3jCIpZtLJSUbM1lV4_U68_RKm4
#https://media.giphy.com/media/ohkdbwhfqQCFq/giphy.gif
#from telebot import types